#!/bin/sh
SCRIPTS=$1
sh $SCRIPTS/ReF_CR.sh MF/ReF_CR
sh $SCRIPTS/ReF_CR.sh MR/ReF_CR
sh $SCRIPTS/ReF_CR.sh MS/ReF_CR
sh $SCRIPTS/ReF_CR.sh RMF/ReF_CR
sh $SCRIPTS/ReF_CR.sh RMR/ReF_CR
sh $SCRIPTS/ReF_CR.sh MS/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh MF/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh MR/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh MS/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh RMF/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh RMR/ReF_CR
sh $SCRIPTS/ReF_CR_ALL.sh RMS/ReF_CR


