#!/bin/sh
SCRIPTS=$1
NROUTERS=$2
ROUTER=0
while [ $ROUTER -ne $NROUTERS ]
do
  sh $SCRIPTS/USERSperROUTER.sh MF $NROUTERS $ROUTER
  sh $SCRIPTS/USERSperROUTER.sh MR $NROUTERS $ROUTER
  sh $SCRIPTS/USERSperROUTER.sh MS $NROUTERS $ROUTER
  sh $SCRIPTS/USERSperROUTER.sh RMF $NROUTERS $ROUTER
  sh $SCRIPTS/USERSperROUTER.sh RMR $NROUTERS $ROUTER
  sh $SCRIPTS/USERSperROUTER.sh RMS $NROUTERS $ROUTER
  ROUTER=$(( $ROUTER + 1 ))
done
